
CREATE TABLE customers (
	CustomerId INTEGER,
	CustomerName VARCHAR(100),
	Address VARCHAR(100),
	City VARCHAR(50),
	State VARCHAR(10),
	Zip VARCHAR(10),
	CREATEDBY VARCHAR(100),
	UPDATEDBY VARCHAR(100),
	CREADTEDDATE DATETIME,
	UPDATEDDATE DATETIME,
	HashKey BIGINT,
	IsActive INTEGER
);

CREATE TABLE accounts (
	AccountId INTEGER,
	CustomerId INTEGER,
	AccountType VARCHAR(50),
	Balance FLOAT,
	CREATEDBY VARCHAR(100),
	UPDATEDBY VARCHAR(100),
	CREADTEDDATE DATETIME,
	UPDATEDDATE DATETIME,
	HashKey BIGINT,
	IsActive INTEGER
);

CREATE TABLE loans (
	LoanId INTEGER,
	CustomerId INTEGER,
	LoanAmount FLOAT,
	InterestRate FLOAT,
	LoanTerm INTEGER,
	CREATEDBY VARCHAR(100),
	UPDATEDBY VARCHAR(100),
	CREADTEDDATE DATETIME,
	UPDATEDDATE DATETIME,
	HashKey BIGINT,
	IsActive INTEGER
);

CREATE TABLE loanpayments (
	PaymentId INTEGER,
	LoanId INTEGER,
	PaymentDate DATETIME,
	PaymentAmount FLOAT,
	CREATEDBY VARCHAR(100),
	UPDATEDBY VARCHAR(100),
	CREADTEDDATE DATETIME,
	UPDATEDDATE DATETIME,
	HashKey BIGINT
);

CREATE TABLE transactions (
	TransactionId INTEGER,
	AccountId INTEGER,
	TransactionDate DATETIME,
	TransactionAmount FLOAT,
	TransactionType VARCHAR(20),
	CREATEDBY VARCHAR(100),
	UPDATEDBY VARCHAR(100),
	CREADTEDDATE DATETIME,
	UPDATEDDATE DATETIME,
	HashKey BIGINT
)